[package]
name = "trafiklab"
version = "0.0.1"
edition = "2024"

[features]
stress = []
resrobot = []

[dependencies]
chrono = "0.4"
reqwest = "0.12"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
tokio = {version = "1.48", features=["full"]}
url = "2.5"
