[package]
name = "trafiklab"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12"
serde = "1.0"
serde_json = "1.0"
thiserror = "2.0"
tokio = {version = "1.48", features=["full"]}
url = "2.5"
